// Turns Google's official "Add to / View in Google Wallet" SVGs into one lazy
// module per mode + language, keyed by lowercase BCP 47 ("vi", "pt-br").
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';

const SOURCES = {
  add: { dir: 'src/assets/add-to-wallet-svg/svg', suffix: '_add_to_google_wallet_' },
  view: { dir: 'src/assets/view-in-google-wallet-svg', suffix: '_view_in_wallet_' },
};
// Google's file prefixes that are not BCP 47.
const ALIASES = {
  cz: 'cs',
  dk: 'da',
  gr: 'el',
  jp: 'ja',
  kh: 'km',
  se: 'sv',
  by: 'be',
  iw: 'he',
  br: 'pt-br',
  pt: 'pt-pt',
  enus: 'en',
  eses: 'es',
  frfr: 'fr',
  'am-et': 'am',
  'gu-in': 'gu',
  'ur-pk': 'ur',
};
// Device language without a region: the most used variant. The view set has
// no plain English, only en-GB/en-AU (same wording).
const BASE_DEFAULTS = { en: 'en-gb', pt: 'pt-br', zh: 'zh-cn' };
const VARIANTS = { 'wallet-button': 'button', 'add-wallet-badge': 'badge' };
const OUT = 'src/generated';

const toKey = (prefix) => {
  const code = prefix.toLowerCase().replace('_', '-');
  // enGB → en-gb, es419 → es-419
  return ALIASES[code] ?? code.replace(/^([a-z]{2})([a-z]{2}|\d{3})$/, '$1-$2');
};

rmSync(OUT, { recursive: true, force: true });
mkdirSync(`${OUT}/google`, { recursive: true });
const loaders = {};
for (const [mode, { dir, suffix }] of Object.entries(SOURCES)) {
  const badges = {};
  for (const file of readdirSync(dir)) {
    // "-1" files are alternate cuts of a language already present.
    const match = file.match(new RegExp(`^(.+)${suffix}(wallet-button|add-wallet-badge)\\.svg$`));
    if (!match) continue;
    const key = toKey(match[1]);
    (badges[key] ??= {})[VARIANTS[match[2]]] = readFileSync(`${dir}/${file}`, 'utf8').trim();
  }
  for (const [base, key] of Object.entries(BASE_DEFAULTS)) if (!badges[base] && badges[key]) badges[base] = badges[key];
  loaders[mode] = Object.keys(badges).sort();
  for (const key of loaders[mode]) {
    const { button, badge } = badges[key];
    if (!button || !badge) throw new Error(`${mode}/${key}: missing button or badge SVG`);
    writeFileSync(
      `${OUT}/google/${mode}-${key}.ts`,
      `export const button: string = ${JSON.stringify(button)};\nexport const badge: string = ${JSON.stringify(badge)};\n`,
    );
  }
}
const map = (mode) =>
  loaders[mode].map((key) => `    '${key}': () => import('./google/${mode}-${key}.js'),`).join('\n');
writeFileSync(
  `${OUT}/google-badges.ts`,
  `// Generated by scripts/google-badges.mjs.
export type GoogleBadge = { button: string; badge: string };

export const GOOGLE_BADGES: Record<'add' | 'view', Record<string, () => Promise<GoogleBadge>>> = {
  add: {
${map('add')}
  },
  view: {
${map('view')}
  },
};
`,
);
console.log(`Google Wallet badges: add ${loaders.add.length}, view ${loaders.view.length} languages`);
